### PR TITLE
Added support for SonarQube Generic Coverage XML format

### PR DESCRIPTION
**Pull request by nibant**
Based on cobertura.R. This is a proposed solution for #413

### CODE REVIEW

**Comment by jimhester** [comment]
I think it looks good, 
can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`, then I can merge this!

**Comment by Delfic** [comment]
Done! Thank you so much 👍

**Comment by nibant** [comment]
Great! Thank you very much @jimhester!

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
