### PR TITLE
Add option to skip clean_objects

### PR DESCRIPTION
**Pull request by jpritikin**
Here's how I solved #375. You probably have a better solution, but this is tested and works.

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks, I think this is fine, but can we name the argument `pre_clean` and make the default `TRUE`? Also can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by jpritikin** [comment]
How's it look now?

**Comment by jpritikin** [comment]
How to get this merged? These test failures don't look like my fault.

**Comment by jimhester** [comment]
Great work, this package is now better thanks to you!

Thanks!! You are da bomb!

**Pull request merged**
