### PR TITLE
Support Google Cloud Build

### PR DESCRIPTION
**Pull request by MarkEdmondson1234**
This lets googleCloudRunner upload covr reports directly without needing travis as well.

I referenced the API arguments here: https://docs.codecov.io/reference#upload

I enabled the default substitution variables available in Google Cloud Build here: https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values - creating them as environment arguments for covr to discover with the prefix `GCB_`

I have some successful Cloud Build reports uploading with this code here: https://app.codecov.io/gh/MarkEdmondson1234/measurementProtocol/

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks, this looks good!

Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by MarkEdmondson1234** [comment]
Ah thanks!  Its been a while so had to remind myself, but I've been using my fork extensively for example during development of https://app.codecov.io/gh/MarkEdmondson1234/googleCloudRunner

**Comment by jimhester** [comment]
Sorry about the delay, I think I was not actively watching this repo when you sent the PR, so didn't see it right away.

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
